services:
  server:
    build:
      context: ./apps/server
    container_name: bebop-server
    command: start
    restart: unless-stopped
    ports:
      - 3000
    volumes:
      - ./apps/server/db/bebop.sqlite:/app/db/bebop.sqlite
      - ./apps/server/bebop.yml:/app/bebop.yml
