services:
  redis:
    image: redis:alpine
    container_name: bebop-redis
    restart: unless-stopped
    ports:
      - 6379:6379

  server:
    build:
      context: ./apps/server
    container_name: bebop-server
    command: start:api
    restart: unless-stopped
    env_file:
      - ./apps/server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/server/db/bebop.sqlite:/app/db/bebop.sqlite
      - ./apps/server/bebop.yml:/app/bebop.yml
    depends_on:
      - redis

  worker:
    build:
      context: ./apps/server
    container_name: bebop-worker
    command: start:worker
    restart: unless-stopped
    env_file:
      - ./apps/server/.env
    volumes:
      - ./apps/server/db/bebop.sqlite:/app/db/bebop.sqlite
      - ./apps/server/bebop.yml:/app/bebop.yml
    depends_on:
      - redis
