name: Build Images and Push to Registry
on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Image Build and Push
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to Registry
        id: build_push
        uses: docker/build-push-action@v5
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: ./apps/server
          push: true
          tags: ghcr.io/gokceno/bebop-server:latest
